# Generated by Django 4.2.1 on 2023-07-03 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='наименование')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='URl')),
                ('contents', models.TextField(verbose_name='содержание')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='дата создания')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='изображение')),
                ('is_published', models.BooleanField(default=True, verbose_name='признак публикации')),
                ('views_number', models.IntegerField(default=0, verbose_name='Количество просмотров')),
            ],
            options={
                'verbose_name': 'блог',
                'verbose_name_plural': 'блоги',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='наименование')),
                ('description', models.CharField(max_length=500, verbose_name='описание')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='URl')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='наименование')),
                ('author', models.CharField(max_length=150, verbose_name='автор')),
                ('description', models.CharField(max_length=500, verbose_name='описание')),
                ('category', models.CharField(max_length=150, verbose_name='категория')),
                ('price', models.IntegerField(verbose_name='цена за покупку')),
                ('creation_date', models.DateField(verbose_name='дата создания')),
                ('last_change_date', models.DateField(verbose_name='дата последнего изменения')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='изображение')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='URl')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
                'ordering': ('name',),
            },
        ),
    ]
