# Generated by Django 4.2.1 on 2023-05-30 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='наименование')),
                ('description', models.CharField(max_length=500, verbose_name='описание')),
                ('category', models.CharField(max_length=150, verbose_name='категория')),
                ('price', models.IntegerField(verbose_name='цена за покупку')),
                ('creation_date', models.DateTimeField(verbose_name='дата создания')),
                ('last_change_date', models.DateTimeField(verbose_name='дата последнего изменения')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='изображение')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
                'ordering': ('name',),
            },
        ),
    ]
