# Generated by Django 4.2.1 on 2023-06-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.CharField(default=None, max_length=150, verbose_name='автор'),
            preserve_default=False,
        ),
    ]
