# Generated by Django 4.2.1 on 2023-06-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_product_last_change_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='наименование')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='URl')),
                ('contents', models.CharField(max_length=500, verbose_name='описание')),
                ('creation_date', models.DateField(verbose_name='дата создания')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='изображение')),
                ('is_published', models.BooleanField(default=True, verbose_name='признак публикации')),
                ('views_number', models.IntegerField(default=0, verbose_name='Количество просмотров')),
            ],
            options={
                'verbose_name': 'блог',
                'verbose_name_plural': 'блоги',
                'ordering': ('name',),
            },
        ),
    ]
