# Generated by Django 4.2.1 on 2023-07-17 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'permissions': [('can_cancell_publication', 'Can cancell publication')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
